version: '3'

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./kafka/init.sh:/init.sh
    depends_on:
      - zookeeper
  
  producer:
    build: ./producers
    container_name: producer_kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producers:/usr/src/app

  producer2:
    build: ./producers
    container_name: producer_kafka2
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producers:/usr/src/app

  producer3:
    build: ./producers
    container_name: producer_kafka3
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producers:/usr/src/app

  consumer:
    build: ./consumers
    container_name: consumer_kafka
    #deploy: 
    #  replicas: 5
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumers:/usr/src/app

###################-POSTGRESQL-##########################
  db:
    container_name: db
    image: postgres:16.0-alpine3.18
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=proyecto
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5433:5432"

###################-PG_ADMIN-##########################
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - db
    logging:
      driver: none

    